[package]
name = "hilog-sys"
version = "0.1.0"
edition = "2021"
keywords = ["OpenHarmony", "HarmonyOS", "hilog", "log"]
description = "Rust bindings to the HiLog logging system of OpenHarmony"
repository = "https://github.com/huawei-drc/hilog-sys"
license = "Apache-2.0"
